version: '2.3'

networks:
  back:
    driver: bridge

services:
  db:
    restart: always
    image: postgres:alpine
    cpu_count: 2
    cpu_percent: 50
    mem_limit: 1gb
    memswap_limit: 2gb
    mem_reservation: 512m
    volumes:
      - /data/docker/asterisk/data/postgresql:/var/lib/postgresql/data
    env_file:
      - system.env
      - postgres.env
    networks:
      back:
        aliases:
          - asterisk_db
  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DESIGN=nette
    ports:
      - 8081:8080
    networks:
      - back

  voip:
    restart: always
    image: blackojack/asterisk
    cpu_count: 4
    cpu_percent: 80
    mem_limit: 1gb
    memswap_limit: 2gb
    mem_reservation: 512m
    tmpfs: /tmp/asterisk
    ports:
      - 5060:5060/udp
      - 4569:4569/udp
      - 16364-16394:16364-16394/udp
    depends_on:
      - db
    env_file:
      - system.env
      - postgres.env
      - asterisk.env
    networks:
      - back
